streamlit==0.71.0
pandas==1.1.3
numpy==1.19.2
pandas-profiling==2.10.0
streamlit-pandas-profiling==0.1.1
version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
